workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_PUBLIC_API_BASE_URL: "http://api.klordenergy.com:4001"
      node: 20.19.0
      npm: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm ci
      - name: Set up Expo
        script: |
          npx expo install
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android APK/AAB
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - viratvaroniya31@gmail.com
        notify:
          success: true
          failure: true
